version: '3.9'

services:
  db:
    image: postgres
    shm_size: 128mb
    container_name: postgres
    environment:
      POSTGRES_DB: nastya
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: nastya
    ports:
      - "5432:5432"
    networks:
      - postgres_bd

  adminer:
    image: adminer
    restart: always
    ports:
      - "4321:8080"
    depends_on:
      - db
    networks:
      - postgres_bd

  my-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
        - db
    networks:
      - postgres_bd

networks:
  postgres_bd:
    driver: bridge